version: '3'
services:
  consul:
    image: consul:1.7
    container_name: consul_server
    ports:
      - "8500:8500"
      - "8501:8501"
    command: "agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0 --https-port=8501"

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional
    environment:
      - COLLECTOR_OTLP_ENABLED=true
